name: Deploy Insight Public

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy_main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build App
        run: |
          npm ci
          npm run build

      - name: Deploy to server (production)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/next-insight-public
            git checkout main
            git pull
            npm install
            npm run build
            pm2 restart public

  deploy_dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build App
        run: |
          npm ci
          npm run build

      - name: Deploy to server (development)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/dev/next-insight-public
            git checkout dev
            git pull
            npm install
            npm run build
            pm2 restart dev-public
